### ISSUE TITLE
Add OpenAL to stackage.

### ISSUE THREAD

**Issue by Mokosha** [haskell-openal/OpenAL#1]
Hi -- not really related to this repository per se. Are there any plans to add OpenAL to the [stackage server](https://github.com/fpco/stackage/blob/master/build-constraints.yaml)? If not, does anything need to be done to OpenAL to get it to that point?

**Comment by svenpanne** [comment]
Having OpenAL in stackage would be a good idea IMHO, the only point is: I am not sure how stackage handles ``extra-libraries:`` in .cabal files. The OpenAL package needs, well, the ``openal`` library, which is not installed by default on most distros. So the stackage build server somehow needs to have this library installed, but I have no clue how this works. Looking at the list of packages on stackage there seems to be some way, but the details are totally opaque to me.

Perhaps I should just issue a pull request to ``build-constraints.yaml`` for OpenAL and see how things work out. Probably I should just do the same for the ALUT package, which needs the ``alut`` library.

**Comment by svenpanne** [comment]
OK, I've created https://github.com/fpco/stackage/pull/2129, let's see how this works...

**Comment by svenpanne** [comment]
OK, both ``OpenAL`` and ``ALUT`` are in Stackage Nightly now.

Thanks for reminding me! :-)

**Comment by Mokosha** [comment]
Sweet, thanks!
